version: '3.7'
services:
  db:
    ports:
    - "5432:5432"
    image: postgres
    restart: always
    environment:
     POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - "9901:8080"
