bot:
  auth:
    username: MakeFr_Bot
    token: 2052876180:AAEFrNl-2U3t-oHEhBmtNvwc4bbFyfzIJ9w
spring:
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root